<a href="https://colab.research.google.com/github/doij1301/BSQ110_Projet1/blob/master/La_porte_au_tr%C3%A9sor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from math import *

# Portes quantiques

In [2]:
i_gate = np.array([[1, 0],
                   [0, 1]])
h_gate = np.sqrt(0.5)*np.array([[1, 1], 
                                [1, -1]])
x_gate = np.array([[0, 1], 
                   [1, 0]])
cx10_gate = np.array([[1, 0, 0, 0],
                      [0, 0, 0, 1],
                      [0, 0, 1, 0],
                      [0, 1, 0, 0]])
swap_gate = np.array([[1, 0, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 1, 0, 0], 
                      [0, 0, 0, 1]])




Fonction permettant de définir les portes cnot (autre que cx10)

In [3]:
def cx_gate(qbit_controled, qbit_controler):
  
  if qbit_controled > qbit_controler :
    cnot_gate = cx10_gate
    i_exponent_gate = np.array([1])
    for i in range(qbit_controled - qbit_controler - 1) :
      i_exponent_gate = np.kron(i_gate, i_exponent_gate)
      cnot_gate = np.kron(swap_gate, i_exponent_gate) @ np.kron(i_gate, cnot_gate) @ np.kron(swap_gate, i_exponent_gate)
  
  elif qbit_controled < qbit_controler :
    cnot_gate = swap_gate @ cx10_gate @ swap_gate
    i_exponent_gate = np.array([1])
    for i in range(qbit_controler - qbit_controled -1) :
      i_exponent_gate = np.kron(i_gate, i_exponent_gate)
      cnot_gate = np.kron(swap_gate, i_exponent_gate) @ np.kron(i_gate, cnot_gate) @ np.kron(swap_gate, i_exponent_gate)

  else :
    print("C'est probablement une porte X")

  return cnot_gate

cx_gate(0, 2)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])

# Initialisation

In [4]:
# matrice équivalente aux 2 portes h
hih_gate = np.kron(np.kron(h_gate, i_gate), h_gate)

# matrice de la porte cnot (pour le circuit à 3 qbites)
icx10_gate = np.kron(i_gate, cx10_gate)

# matrice représentant l'initialisation
initialisation_gate = icx10_gate @ hih_gate
print(initialisation_gate)

[[ 0.5  0.5  0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5 -0.5  0.   0.   0.5 -0.5]
 [ 0.   0.   0.5  0.5  0.   0.   0.5  0.5]
 [ 0.5 -0.5  0.   0.   0.5 -0.5  0.   0. ]
 [ 0.5  0.5  0.   0.  -0.5 -0.5  0.   0. ]
 [ 0.   0.   0.5 -0.5  0.   0.  -0.5  0.5]
 [ 0.   0.   0.5  0.5  0.   0.  -0.5 -0.5]
 [ 0.5 -0.5  0.   0.  -0.5  0.5  0.   0. ]]
